version: "3"
services:
  web:
    build: ./frontend
    image: gleam-frontend
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared

  server:
    build: ./backend
    image: gleam-backend
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
